Name: Sujal Banset

Uni ID: 2357525

Group: L6CG19

# **TO - DO - Task**

**Exercise on Functions:**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
# Task - 1:
def transform_measurement(input_value, conversion_key):
    transformations = {
        "meter_to_feet": (3.28084, "meters", "feet"),
        "feet_to_meter": (0.3048, "feet", "meters"),
        "kilo_to_pound": (2.20462, "kilograms", "pounds"),
        "pound_to_kilo": (0.453592, "pounds", "kilograms"),
        "liter_to_gallon": (0.264172, "liters", "gallons"),
        "gallon_to_liter": (3.78541, "gallons", "liters")
    }

    if conversion_key in transformations:
        factor, from_unit, to_unit = transformations[conversion_key]
        return input_value * factor, from_unit, to_unit
    else:
        return "Unsupported transformation."

def start_converter():
    print("Unit Transformation Tool")
    print("Options:")
    print("- Length: meter_to_feet, feet_to_meter")
    print("- Weight: kilo_to_pound, pound_to_kilo")
    print("- Volume: liter_to_gallon, gallon_to_liter")

    try:
        user_choice = input("Enter the transformation type (e.g., 'meter_to_feet'): ").strip()
        user_value = float(input("Enter the value to transform: "))
        output = transform_measurement(user_value, user_choice)
        if isinstance(output, str):
            print(f"Error: {output}")
        else:
            transformed_value, from_unit, to_unit = output
            print(f"Result: {user_value:.2f} {from_unit} = {transformed_value:.2f} {to_unit}")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")
    except Exception as e:
        print(f"An unexpected issue occurred: {e}")

start_converter()

Unit Transformation Tool
Options:
- Length: meter_to_feet, feet_to_meter
- Weight: kilo_to_pound, pound_to_kilo
- Volume: liter_to_gallon, gallon_to_liter
Enter the transformation type (e.g., 'meter_to_feet'): kilo_to_pound
Enter the value to transform: 75
Result: 75.00 kilograms = 165.35 pounds


Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
#Task - 2:
def compute_total(values):
    return sum(values)

def compute_mean(values):
    return sum(values) / len(values) if values else None

def get_highest(values):
    return max(values)

def get_lowest(values):
    return min(values)

def run_program():
    print("Choose an operation:")
    print("1: Total Sum")
    print("2: Mean Value")
    print("3: Highest Number")
    print("4: Lowest Number")

    op = int(input("Enter operation number (1-4): "))

    raw_input = input("Enter numbers separated by spaces or commas: ")
    num_list = [float(num) for num in raw_input.replace(",", " ").split()]

    if op == 1:
        print("Total Sum:", compute_total(num_list))
    elif op == 2:
        print("Mean Value:", compute_mean(num_list))
    elif op == 3:
        print("Highest Number:", get_highest(num_list))
    elif op == 4:
        print("Lowest Number:", get_lowest(num_list))
    else:
        print("Invalid option!")

run_program()

Choose an operation:
1: Total Sum
2: Mean Value
3: Highest Number
4: Lowest Number
Enter operation number (1-4): 2
Enter numbers separated by spaces or commas: 2, 4, 5, 6, 8
Mean Value: 5.0


**Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
3def extract_every_other(lst):
    return lst[::2]  # Directly slice the list to get every other element

def get_user_list():
    try:
        num_elements = int(input("How many numbers would you like to enter? "))
        if num_elements <= 0:
            return print("Please enter a positive number.")

        user_list = [int(input(f"Enter number {i + 1}: ")) for i in range(num_elements)]
        return user_list
    except ValueError:
        print("Invalid input! Please enter a valid number.")
        return []

print("Let's create a list of numbers and extract every other element.")

user_list = get_user_list()
if user_list:
    print("You entered:", user_list)
    print("Every other element:", extract_every_other(user_list))

Let's create a list of numbers and extract every other element.
How many numbers would you like to enter? 4
Enter number 1: 12
Enter number 2: 23
Enter number 3: 45
Enter number 4: 56
You entered: [12, 23, 45, 56]
Every other element: [12, 45]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [4]:
# Slice a Sublist:
def get_sublist(lst, start, end):
    if start < 0 or end >= len(lst) or start > end:
        return []

    sublist = lst[start:end + 1]
    return sublist

example_list = [1, 2, 3, 4, 5, 6]
result = get_sublist(example_list, 2, 4)
print(result)

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
# Reverse a List Using Slicing:
def reverse_list(lst):
    return lst[::-1]

input_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']
reversed_list = reverse_list(input_list)
print("Original List:", input_list)
print("Reversed List:", reversed_list)

Original List: ['apple', 'banana', 'cherry', 'date', 'elderberry']
Reversed List: ['elderberry', 'date', 'cherry', 'banana', 'apple']


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
# Remove the First and Last Elements:
def remove_first_last(lst):

    if len(lst) <= 2:
        return []
    return lst[1:-1]

sample_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']
result = remove_first_last(sample_list)
print(result)

['banana', 'cherry', 'date']


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
# Get the First n Elements:
def get_first_n(lst, n):
    return lst[:n] if n >= 0 else []

try:
    user_input = input("Enter a list of elements (comma-separated): ")
    user_list = [item.strip() for item in user_input.split(",")]

    n = int(input("Enter the number of elements to extract: "))

    result = get_first_n(user_list, n)
    print(f"The first {n} elements are: {result}")

except ValueError:
    print("Invalid input! Please ensure you enter a valid list and integer for 'n'.")

Enter a list of elements (comma-separated): 1, 2, 3, 4, 5, 6
Enter the number of elements to extract: 2
The first 2 elements are: ['1', '2']


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    if n <= 0:
        return []
    elif n > len(lst):
        return lst
    return lst[-n:]

user_input = input("Enter a list of elements separated by spaces: ")
user_list = user_input.split()
try:
    n = int(input("Enter the number of elements you want to extract from the end: "))
except ValueError:
    print("Please enter a valid integer for the number of elements.")
    exit()

result = get_last_n(user_list, n)
print(f"The last {n} elements of your list are: {result}")

Enter a list of elements separated by spaces: 2, 4, 6, 8, 10, 12
Enter the number of elements you want to extract from the end: 3
The last 3 elements of your list are: ['8,', '10,', '12']


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between. • Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
 – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
# Extract Elements in Reverse Order:
def reverse_skip(lst):
    return lst[-2::-2]

user_input = input("Enter a list of elements separated by spaces: ")
user_list = user_input.split()
result = reverse_skip(user_list)
print(f"The reversed list with every second element skipped is: {result}")


Enter a list of elements separated by spaces: 3, 5, 7, 9, 12
The reversed list with every second element skipped is: ['9,', '5,']


# **Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [10]:
#Flatten a Nested List:
def flatten(lst):

    stack = lst[::-1]
    result = []

    while stack:
        current = stack.pop()
        if isinstance(current, list):
            stack.extend(current[::-1])
        else:
            result.append(current)

    return result

nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)
print(flattened_list)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [11]:
# Accessing Nested List Elements:
def access_nested_element(lst, indices):
    current = lst
    for index in indices:
        current = current[index]
    return current

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [12]:
#Sum of All Elements in a Nested List:
def sum_nested(lst):
    return sum(
        sum_nested(item) if isinstance(item, list) else item
        for item in lst
    )

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)

21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [13]:
#Remove Specific Element from a Nested List:
def remove_element(lst, elem):
    return [
        remove_element(item, elem) if isinstance(item, list) else item
        for item in lst
        if item != elem
    ]

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print(result)

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [14]:
#Find the Maximum Element in a Nested List:
def find_max(lst):
    stack = list(lst)
    max_value = float('-inf')

    while stack:
        current = stack.pop()

        if isinstance(current, list):
            stack.extend(current)
        else:
            max_value = max(max_value, current)

    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [15]:
#Count Occurrences of an Element in a Nested List:
def count_occurrences(lst, elem):

    def traverse(nested):
        for item in nested:
            if isinstance(item, list):
                yield from traverse(item)
            elif item == elem:
                yield 1

    return sum(traverse(lst))

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print(result)

3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [16]:
#Flatten a List of Lists of Lists:
def deep_flatten(lst):
    stack = list(lst)
    result = []

    while stack:
        current = stack.pop()
        if isinstance(current, list):
            stack.extend(current[::-1])
        else:
            result.append(current)

    return result

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(nested_list)
print(flattened_list)

[5, 6, 7, 8, 1, 2, 3, 4]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
#Nested List Average:
def average_nested(lst):
    stack = list(lst)
    total = 0
    count = 0

    while stack:
        current = stack.pop()

        if isinstance(current, list):
            stack.extend(current)
        else:
            total += current
            count += 1

    return total / count if count > 0 else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5


# **To - Do - NumPy**

**Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

In [18]:
import numpy as np

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [19]:
# Task 1: Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

Empty Array (2x2):
 [[1.97317976e-316 0.00000000e+000]
 [1.68891191e-052 4.17576778e-057]]


In [20]:
# Task 2: Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)



All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
# Task 3: Return a new array of given shape and type, filled with fill value
fill_value = 2
shape = (3, 3)
filled_array = np.full(shape, fill_value, dtype=int)
print("\nFilled Array (3x3 with 7s):\n", filled_array)


Filled Array (3x3 with 7s):
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [22]:
# Task 4: Return a new array of zeros with same shape and type as a given array
reference_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Reference Array:\n", zeros_like_array)



Zeros Like Reference Array:
 [[0 0 0]
 [0 0 0]]


In [23]:
# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Reference Array:\n", ones_like_array)


Ones Like Reference Array:
 [[1 1 1]
 [1 1 1]]


In [24]:
# Task 6: Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Converted NumPy Array:
 [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [25]:
# Create an array with values ranging from 10 to 49.
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
# Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix with Values 0 to 8:\n", matrix_3x3)


3x3 Matrix with Values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3, dtype=int)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [28]:
#Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of Size 30:\n", random_array)
print("Mean of the Array:", mean_value)


Random Array of Size 30:
 [0.41800627 0.50360345 0.5742206  0.53306338 0.75888015 0.58468524
 0.20000877 0.05354923 0.76062495 0.27553894 0.66035022 0.99940841
 0.23126872 0.30454666 0.22475072 0.76451196 0.33965808 0.68172894
 0.57580919 0.43461994 0.1731282  0.56832428 0.53955503 0.07890003
 0.15319488 0.52567213 0.58114672 0.29507126 0.57594007 0.44229806]
Mean of the Array: 0.4604021487230533


In [29]:
# Create a 10X10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


10x10 Random Array:
 [[0.3970686  0.65991927 0.79468679 0.87331436 0.44033019 0.2293096
  0.88168283 0.87058683 0.4527589  0.67348279]
 [0.91081159 0.96593415 0.76402741 0.68792352 0.90389485 0.13379011
  0.39594296 0.59776812 0.15424918 0.86569242]
 [0.61224211 0.87346571 0.15230225 0.1153397  0.54478856 0.9411051
  0.49659147 0.57224232 0.98154979 0.12880436]
 [0.96675928 0.71740003 0.91474197 0.14790838 0.72994916 0.65677703
  0.06406771 0.6629822  0.52657697 0.68837048]
 [0.36903209 0.60535022 0.78100707 0.99400907 0.07579763 0.82502952
  0.56644473 0.06974557 0.39424887 0.09271047]
 [0.59560286 0.73717837 0.32860608 0.789422   0.93990567 0.86102764
  0.32906617 0.77318935 0.2332041  0.55340053]
 [0.02451558 0.26934591 0.02826645 0.13114822 0.58972761 0.06065624
  0.71320273 0.77693235 0.43272351 0.41030534]
 [0.62791283 0.54935231 0.97994472 0.1855861  0.99495347 0.45545572
  0.06307807 0.29954207 0.5998913  0.79814612]
 [0.21779072 0.92365563 0.3992223  0.99144124 0.07119511 0.4

In [30]:
#Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10, dtype=int)
zero_array[4] = 1
print("\nZero Array with 5th Element Replaced:\n", zero_array)


Zero Array with 5th Element Replaced:
 [0 0 0 0 1 0 0 0 0 0]


In [31]:
#Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nOriginal Array:\n", arr)
print("Reversed Array:\n", reversed_arr)


Original Array:
 [1 2 0 0 4 0]
Reversed Array:
 [0 4 0 0 2 1]


In [32]:
#Create a 2d array with 1 on border and 0 inside.
border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)


2D Array with 1 on Border and 0 Inside:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [33]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)



8x8 Checkerboard Pattern:
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [34]:
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [35]:
# 1. Add the two array.
add_result = x + y
print("Addition of x and y:")
print(add_result)

Addition of x and y:
[[ 6  8]
 [10 13]]


In [36]:
# 2. Subtract the two array.
subtract_result = x - y
print("\nSubtraction of x and y:")
print(subtract_result)


Subtraction of x and y:
[[-4 -4]
 [-4 -3]]


In [37]:
# 3. Multiply the array with any integers of your choice.
multiply_result_x = x * 3
multiply_result_y = y * 2
print("\nMultiplication of x by 3:")
print(multiply_result_x)
print("\nMultiplication of y by 2:")
print(multiply_result_y)


Multiplication of x by 3:
[[ 3  6]
 [ 9 15]]

Multiplication of y by 2:
[[10 12]
 [14 16]]


In [38]:
# 4. Find the square of each element of the array.
square_x = np.square(x)
square_y = np.square(y)
print("\nSquare of each element in x:")
print(square_x)
print("\nSquare of each element in y:")
print(square_y)



Square of each element in x:
[[ 1  4]
 [ 9 25]]

Square of each element in y:
[[25 36]
 [49 64]]


In [39]:
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [40]:
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenation of x and y along rows:")
print(concat_xy_rows)
print("\nConcatenation of v and w along columns:")
print(concat_vw_columns)


Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 11]
 [10 12]]


In [41]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=1)
    print("\nConcatenation of x and v along rows:")
    print(concat_xv)
except Exception as e:
    print("\nError while concatenating x and v:", e)


Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [42]:
# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [43]:
# 1. Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A⁻¹ =\n", I)

A * A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [44]:
#2. Prove AB ̸= BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nA * B =\n", AB)
print("B * A =\n", BA)
print("\nIs A * B equal to B * A?", np.array_equal(AB, BA))


A * B =
 [[23 13]
 [51 29]]
B * A =
 [[36 44]
 [13 16]]

Is A * B equal to B * A? False


In [45]:
#3. Prove (AB)^T = B^TA^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)ᵀ =\n", AB_T)
print("Bᵀ * Aᵀ =\n", B_T_A_T)
print("\nIs (AB)ᵀ equal to Bᵀ * Aᵀ?", np.array_equal(AB_T, B_T_A_T))


(AB)ᵀ =
 [[23 51]
 [13 29]]
Bᵀ * Aᵀ =
 [[23 51]
 [13 29]]

Is (AB)ᵀ equal to Bᵀ * Aᵀ? True


In [47]:
# 4. Solve the system of linear equations using inverse methods
# Represent the system as AX = B
# Matrix A (coefficients) and B (right-hand side values)
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

In [48]:
# Solve for X using inverse method: X = A⁻¹ * B
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("\nSolution for the system of equations (X = [x, y, z]):")
print(X)



Solution for the system of equations (X = [x, y, z]):
[ 2.  1. -2.]


In [49]:
# 5. Solve the same system using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve:")
print(X_solve)


Solution using np.linalg.solve:
[ 2.  1. -2.]


# **10.2 Experiment: How Fast is Numpy?**

In [50]:
import time
import numpy as np

# Define sizes
SIZE = 1_000_000
MATRIX_SIZE = 1000

# Initialize Python lists
list1 = list(range(SIZE))
list2 = list(range(SIZE))

# Initialize NumPy arrays
array1 = np.arange(SIZE)
array2 = np.arange(SIZE)

# 1. Element-wise Addition
start_time = time.perf_counter()
list_addition = [a + b for a, b in zip(list1, list2)]
list_addition_time = time.perf_counter() - start_time
print(f"Python Lists Addition Time: {list_addition_time:.5f} seconds")

start_time = time.perf_counter()
numpy_addition = array1 + array2
numpy_addition_time = time.perf_counter() - start_time
print(f"NumPy Arrays Addition Time: {numpy_addition_time:.5f} seconds")

# 2. Element-wise Multiplication
start_time = time.perf_counter()
list_multiplication = [a * b for a, b in zip(list1, list2)]
list_multiplication_time = time.perf_counter() - start_time
print(f"\nPython Lists Multiplication Time: {list_multiplication_time:.5f} seconds")

start_time = time.perf_counter()
numpy_multiplication = array1 * array2
numpy_multiplication_time = time.perf_counter() - start_time
print(f"NumPy Arrays Multiplication Time: {numpy_multiplication_time:.5f} seconds")

# 3. Dot Product
start_time = time.perf_counter()
dot_product = sum(a * b for a, b in zip(list1, list2))
list_dot_product_time = time.perf_counter() - start_time
print(f"\nPython Lists Dot Product Time: {list_dot_product_time:.5f} seconds")

start_time = time.perf_counter()
numpy_dot_product = np.dot(array1, array2)
numpy_dot_product_time = time.perf_counter() - start_time
print(f"NumPy Arrays Dot Product Time: {numpy_dot_product_time:.5f} seconds")

# 4. Matrix Multiplication
# Initialize Python matrices
list_matrix1 = [list(range(MATRIX_SIZE)) for _ in range(MATRIX_SIZE)]
list_matrix2 = [list(range(MATRIX_SIZE)) for _ in range(MATRIX_SIZE)]

# Initialize NumPy matrices
numpy_matrix1 = np.arange(MATRIX_SIZE**2).reshape(MATRIX_SIZE, MATRIX_SIZE)
numpy_matrix2 = np.arange(MATRIX_SIZE**2).reshape(MATRIX_SIZE, MATRIX_SIZE)

# Python matrix multiplication
start_time = time.perf_counter()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
list_matrix_multiplication_time = time.perf_counter() - start_time
print(f"\nPython Lists Matrix Multiplication Time: {list_matrix_multiplication_time:.5f} seconds")

# NumPy matrix multiplication
start_time = time.perf_counter()
numpy_matrix_multiplication = np.matmul(numpy_matrix1, numpy_matrix2)
numpy_matrix_multiplication_time = time.perf_counter() - start_time
print(f"NumPy Arrays Matrix Multiplication Time: {numpy_matrix_multiplication_time:.5f} seconds")


Python Lists Addition Time: 0.09701 seconds
NumPy Arrays Addition Time: 0.00949 seconds

Python Lists Multiplication Time: 0.11540 seconds
NumPy Arrays Multiplication Time: 0.00972 seconds

Python Lists Dot Product Time: 0.07968 seconds
NumPy Arrays Dot Product Time: 0.00192 seconds

Python Lists Matrix Multiplication Time: 172.52304 seconds
NumPy Arrays Matrix Multiplication Time: 2.32783 seconds
